name: Deploy Athena CDK Stack

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy (e.g., dev, staging, prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev    # <-- This tells GitHub to use the 'dev' environment secrets
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}       # Reference secrets here
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1    # You must always specify a region

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (ci or install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      # Example: CDK Deploy step
      - name: CDK Deploy
        run: npx cdk deploy --require-approval never
